name: todo_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get_storage: ^2.0.3
  get: ^4.6.5
  flutter_local_notifications: ^9.7.0
  flutter_native_timezone: ^2.0.0
  intl: ^0.17.0
  google_fonts: ^3.0.1
  date_picker_timeline: ^1.2.3
  sqflite: ^2.0.3
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^1.1.2
  rxdart: ^0.27.5



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"
flutter_icons:
  android: true 
  ios: true
  image_path: "images/appicon.png"
flutter:

  uses-material-design: true

  assets:
    - images/person.jpeg
    - images/task.svg